In [1]:
from qiskit import __version__

print(__version__)

2.3.1


In [8]:
import numpy as np
from qiskit.visualization import array_to_latex

In [5]:
# np.array([1, 0]) --> That is a 1D array, not explicitly a column vector.

# 2 x 1 mx rep. by a 2D array.
ket0 = np.array([[1], [0]])     

ket1 = np.array([[0], [1]])

print(ket0 / 2 + ket1 / 2)


[[0.5]
 [0.5]]


We can also use array to create matrices that can represent operations.


In [6]:
M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])

M = M1 / 2 + M2 / 2

print(M)

[[1.  0.5]
 [0.  0.5]]


Matrix multiplication, including matrix-vector multiplication as a special case, can be performed using the @ operator.

In [7]:
print(M1 @ ket1)
print(M1 @ M2)
print(M @ M)

[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


In [10]:
display(array_to_latex(M1 @ ket1))
display(array_to_latex(M1 @ M2))
display(array_to_latex(M @ M))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>