In [1]:
from qiskit import __version__

print(__version__)

2.3.1


In [ ]:
import numpy as np
from qiskit.visualization import array_to_latex
from qiskit.quantum_info import Statevector

In [5]:
# np.array([1, 0]) --> That is a 1D array, not explicitly a column vector.

# 2 x 1 mx rep. by a 2D array.
ket0 = np.array([[1], [0]])     

ket1 = np.array([[0], [1]])

print(ket0 / 2 + ket1 / 2)


[[0.5]
 [0.5]]


We can also use array to create matrices that can represent operations.


In [6]:
M1 = np.array([[1, 1], [0, 0]])
M2 = np.array([[1, 0], [0, 1]])

M = M1 / 2 + M2 / 2

print(M)

[[1.  0.5]
 [0.  0.5]]


Matrix multiplication, including matrix-vector multiplication as a special case, can be performed using the @ operator.

In [7]:
print(M1 @ ket1)
print(M1 @ M2)
print(M @ M)

[[1]
 [0]]
[[1 1]
 [0 0]]
[[1.   0.75]
 [0.   0.25]]


In [10]:
display(array_to_latex(M1 @ ket1))
display(array_to_latex(M1 @ M2))
display(array_to_latex(M @ M))

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

<IPython.core.display.Latex object>

In [13]:
from numpy import sqrt

# Quantum states are column vectors by default.

u = Statevector([1 / sqrt(2), 1 / sqrt(2)])
v = Statevector([(1 + 2.0j) / 3, -2 / 3])
w = Statevector([1 / 3, 2 / 3])


The Statevector class includes a draw method for displaying state vectors in a variety of ways, including text for plain text, latex for rendered LaTeX, and latex_source for LaTeX code, which can be handy for cutting and pasting into documents. (Use print rather than display to show LaTeX code for best results.)

In [16]:
display(u.draw("text"))
display(u.draw("latex"))
display(u.draw("latex_source"))

[0.70710678+0.j,0.70710678+0.j]

<IPython.core.display.Latex object>

'\\frac{\\sqrt{2}}{2} |0\\rangle+\\frac{\\sqrt{2}}{2} |1\\rangle'